# Generated by Django 2.1.7 on 2019-03-25 11:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_img',
            field=models.ImageField(upload_to='Food_Images'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='order_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FoodOrder_list', to='restaurant_admin.OrderList'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='status',
            field=models.CharField(choices=[('NO', 'Not Ordered'), ('CH', 'Changed Order'), ('OR', 'Ordered'), ('PR', 'Preparing'), ('RE', 'Ready'), ('DE', 'Delivered')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 11, 29, 31, 57833, tzinfo=utc)),
        ),
    ]
